enum BuyerActions {
  SET_BUYER_EMAIL = "SET_BUYER_EMAIL",
  SET_BUYER_FIRSTNAME = "SET_BUYER_FIRSTNAME",
  SET_BUYER_LASTNAME = "SET_BUYER_LASTNAME",
  SET_BUYER_COUNTRY = "SET_BUYER_COUNTRY",
  SET_BUYER_CITY = "SET_BUYER_CITY",
  SET_BUYER_ADDRESS = "SET_BUYER_ADDRESS",
  SET_BUYER_POSTCODE = "SET_BUYER_POSTCODE",
  SET_BUYER_PHONENUMBER = "SET_BUYER_PHONENUMBER",
}

export default BuyerActions;
